services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - wordpress_data:/var/www/wordpress
    depends_on: 
      - wordpress
    restart: on-failure
    networks: 
      - inception

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    env_file: .env
    restart: on-failure
    volumes:
      - mariadb_data:/var/lib/mysql 
    networks: 
      - inception
    
  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    env_file: .env
    restart: on-failure
    volumes:
      - wordpress_data:/var/www/wordpress
    depends_on: 
      - mariadb
    networks: 
      - inception

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mhiguera/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mhiguera/data/wordpress

networks:
  inception:
    driver: bridge
